version: '3.8'

services:
  web:
    build: .
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Allow data to persist when container is restarted
    env_file:
      - .env.prod.db

volumes:
  postgres_data: